name: 'WebRTC Android Builder'
description: 'Build WebRTC Android AAR files automatically in the cloud using GitHub Actions. Universal platform support.'
author: 'bentleypark'

branding:
  icon: 'smartphone'
  color: 'blue'

inputs:
  webrtc_branch:
    description: 'WebRTC branch to build (e.g., branch-heads/7151, branch-heads/7103)'
    required: false
    default: 'branch-heads/7151'
    type: string
  
  target_arch:
    description: 'Target architectures (comma separated)'
    required: false
    default: 'armeabi-v7a,arm64-v8a'
  
  build_config:
    description: 'Build configuration (release or debug)'
    required: false
    default: 'release'

  slack_webhook_url:
    description: 'Slack webhook URL for notifications (optional)'
    required: false
  
  slack_channel:
    description: 'Slack channel for notifications'
    required: false
    type: string
  
  enable_slack_notifications:
    description: 'Enable Slack notifications'
    required: false
    default: 'false'

outputs:
  aar_filename:
    description: 'Generated AAR filename'
    value: ${{ steps.build.outputs.aar_filename }}
  
  download_url:
    description: 'Download URL for artifacts'
    value: ${{ steps.build.outputs.download_url }}
  
  build_info:
    description: 'Build information summary'
    value: ${{ steps.build.outputs.build_info }}

runs:
  using: 'composite'
  steps:
    - name: Setup build environment
      shell: bash
      run: |
        echo "🚀 Starting WebRTC Android AAR build..."
        echo "Branch: ${{ inputs.webrtc_branch }}"
        echo "Architectures: ${{ inputs.target_arch }}"
        echo "Configuration: ${{ inputs.build_config }}"
        
        # Extract branch number and determine milestone
        BRANCH_NUMBER=$(echo "${{ inputs.webrtc_branch }}" | sed 's/.*branch-heads\///')
        echo "Branch number: $BRANCH_NUMBER"
        
        # Attempt to fetch milestone dynamically from Chromium Dash
        echo "Attempting to fetch milestone information from Chromium Dash..."
        
        # Try to fetch from chromiumdash API (fallback to static mapping if fails)
        MILESTONE=""
        if command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
          # Try multiple endpoints to find branch-milestone mapping
          echo "Fetching branch information from Chromium Dash API..."
          
          # Method 1: Try branches endpoint (if it exists)
          BRANCHES_RESPONSE=$(curl -s --max-time 15 "https://chromiumdash.appspot.com/api/v0/branches" 2>/dev/null || echo "")
          
          # Method 2: Try releases endpoint for recent releases
          if [ -z "$BRANCHES_RESPONSE" ] || ! echo "$BRANCHES_RESPONSE" | jq empty >/dev/null 2>&1; then
            echo "Trying releases endpoint..."
            RELEASES_RESPONSE=$(curl -s --max-time 15 "https://chromiumdash.appspot.com/fetch_releases?num=100" 2>/dev/null || echo "")
            
            if [ -n "$RELEASES_RESPONSE" ] && echo "$RELEASES_RESPONSE" | jq empty >/dev/null 2>&1; then
              echo "Successfully fetched releases data, analyzing for branch $BRANCH_NUMBER..."
              
              # Try to find milestone from releases data that might contain branch information
              # This is a simplified approach - real implementation would need to understand the API structure
              POTENTIAL_MILESTONE=$(echo "$RELEASES_RESPONSE" | jq -r --arg branch "$BRANCH_NUMBER" '
                .[] | 
                select(.branch_base_position? and (.branch_base_position | tonumber) <= ($branch | tonumber)) |
                .version | 
                split(".")[0] | 
                ltrimstr("1") | 
                if length > 0 then "M" + . else empty end
              ' 2>/dev/null | head -1)
              
              if [ -n "$POTENTIAL_MILESTONE" ] && [ "$POTENTIAL_MILESTONE" != "null" ]; then
                MILESTONE="$POTENTIAL_MILESTONE"
                echo "Successfully determined milestone from API: $MILESTONE"
              else
                echo "Could not determine milestone from API response"
              fi
            fi
          fi
          
          # If API fetch failed, log it
          if [ -z "$MILESTONE" ]; then
            echo "Dynamic milestone detection failed, falling back to static mapping"
          fi
        else
          echo "curl or jq not available, using static mapping"
        fi
        
        # Static milestone mapping (accurate as of 2024)
        if [ -z "$MILESTONE" ]; then
          echo "Using static milestone mapping..."
          if [ "$BRANCH_NUMBER" -ge 7339 ]; then
            MILESTONE="M140"
          elif [ "$BRANCH_NUMBER" -ge 7258 ]; then
            MILESTONE="M139"
          elif [ "$BRANCH_NUMBER" -ge 7204 ]; then
            MILESTONE="M138"
          elif [ "$BRANCH_NUMBER" -ge 7151 ]; then
            MILESTONE="M137"
          elif [ "$BRANCH_NUMBER" -ge 7103 ]; then
            MILESTONE="M136" 
          elif [ "$BRANCH_NUMBER" -ge 7000 ]; then
            MILESTONE="M135"
          elif [ "$BRANCH_NUMBER" -ge 6845 ]; then
            MILESTONE="M134"
          elif [ "$BRANCH_NUMBER" -ge 6723 ]; then
            MILESTONE="M133"
          else
            # Fallback calculation for very old versions
            MILESTONE="M$((133 - (6723 - BRANCH_NUMBER) / 100))"
          fi
        fi
        
        echo "Detected milestone: $MILESTONE"
        echo "WEBRTC_MILESTONE=$MILESTONE" >> $GITHUB_ENV
        echo "WEBRTC_BRANCH_NUMBER=$BRANCH_NUMBER" >> $GITHUB_ENV

    - name: Free up disk space
      shell: bash
      run: |
        echo "Initial disk space:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        sudo docker image prune -a -f
        echo "Disk space after cleanup:"
        df -h

    - name: Set up build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          python3 \
          python3-pip \
          curl \
          lsb-release \
          sudo \
          xz-utils \
          build-essential

    - name: Setup depot_tools
      shell: bash
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="${PWD}/depot_tools:$PATH"
        echo "${PWD}/depot_tools" >> $GITHUB_PATH
        
        echo "Initializing depot_tools..."
        cd depot_tools
        ./ensure_bootstrap
        cd ..
        
        gclient --version
        echo "GYP_DEFINES=OS=android" >> $GITHUB_ENV
        echo "DEPOT_TOOLS_UPDATE=0" >> $GITHUB_ENV

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "WebRTC Builder"
        git config --global user.email "builder@webrtc.local"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global color.ui false

    - name: Create build workspace
      shell: bash
      run: |
        mkdir -p webrtc-build
        cd webrtc-build
        fetch --nohooks webrtc_android

    - name: Checkout WebRTC branch
      shell: bash
      run: |
        cd webrtc-build/src
        echo "Checking out WebRTC branch: ${{ inputs.webrtc_branch }}"
        git checkout ${{ inputs.webrtc_branch }}
        gclient sync

    - name: Install build dependencies
      shell: bash
      run: |
        cd webrtc-build/src
        sudo ./build/install-build-deps.sh --no-prompt --no-chromeos-fonts

    - name: Configure build
      shell: bash
      run: |
        cd webrtc-build/src
        BUILD_ARGS='
          target_os="android"
          is_debug=${{ inputs.build_config == 'debug' && 'true' || 'false' }}
          is_component_build=false
          is_clang=true
          rtc_include_tests=false
          rtc_build_examples=false
          rtc_use_h264=true
          rtc_enable_protobuf=true
          use_custom_libcxx=false
          treat_warnings_as_errors=false
          use_rtti=true
        '
        
        mkdir -p out/android
        gn gen out/android --args="$BUILD_ARGS"

    - name: Build WebRTC AAR
      id: build
      shell: bash
      run: |
        cd webrtc-build/src
        
        IFS=',' read -ra ARCH_ARRAY <<< "${{ inputs.target_arch }}"
        ARCH_ARGS=""
        for arch in "${ARCH_ARRAY[@]}"; do
          arch=$(echo "$arch" | xargs)
          ARCH_ARGS="$ARCH_ARGS --arch $arch"
        done
        
        # Generate AAR filename with detected milestone
        MILESTONE_LOWER=$(echo "$WEBRTC_MILESTONE" | tr '[:upper:]' '[:lower:]')
        AAR_FILENAME="libwebrtc-${MILESTONE_LOWER}-${{ github.run_number }}.aar"
        echo "aar_filename=$AAR_FILENAME" >> $GITHUB_OUTPUT
        
        echo "Building WebRTC AAR with architectures: $ARCH_ARGS"
        echo "Milestone: $WEBRTC_MILESTONE, Branch: ${{ inputs.webrtc_branch }}"
        python3 tools_webrtc/android/build_aar.py $ARCH_ARGS \
          --build-dir out/android \
          --output "$AAR_FILENAME" \
          --extra-gn-args "is_debug=${{ inputs.build_config == 'debug' && 'true' || 'false' }}"
        
        echo "download_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
        echo "build_info=WebRTC $WEBRTC_MILESTONE AAR built successfully" >> $GITHUB_OUTPUT

    - name: Send Slack notification
      if: ${{ inputs.enable_slack_notifications == 'true' && inputs.slack_webhook_url != '' }}
      shell: bash
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "channel": "${{ inputs.slack_channel }}",
              "text": "🎉 *WebRTC Android AAR Build Success!*\n\n📋 *Build Information:*\n• Milestone: `'$WEBRTC_MILESTONE'`\n• Branch: `${{ inputs.webrtc_branch }}`\n• Architectures: `${{ inputs.target_arch }}`\n• Configuration: `${{ inputs.build_config }}`\n\n📦 *AAR File:* `${{ steps.build.outputs.aar_filename }}`\n\n🔗 [Download Artifacts](${{ steps.build.outputs.download_url }})"
            }' \
            ${{ inputs.slack_webhook_url }}
        fi